### ISSUE TITLE
Fonts are not loaded correctly with qwc-qgis-server since version 3.28.6

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-qgis-server#6]
To include additional fonts, change the locale and other things I am building an own qwc-qgis-server image based on yours. Since the Dockerfile and entrypoint.sh files are changed plainly, I had to rewrite our files as well to work with the current versions of qgis server. 
Unfortunately I don't get the fonts work properly. They are used within GetMap requests and also on the print templates in a correct way. But in the legendGraphics the font is not used and I am getting the following error within the logs:
```sh
QFont::fromString: Invalid description '(empty)'
QPainter::scale: Painter not active
```
Any hints, where this could come from?

My Dockerfile:
```Dockerfile
FROM sourcepole/qwc-qgis-server:3.28.8

RUN apt-get update \
    && apt-get install --no-install-recommends -y cifs-utils \
    && rm -rf /var/lib/apt/lists/*

ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8

# ENV variables that will be used to configure QGIS server FCGI
[...]
# Add apache config for QGIS server
ADD qgis3-server.conf.template /etc/apache2/templates/qgis-server.conf.template

# Add font and plugins folders
ADD fonts /usr/local/share/fonts
ADD plugins /usr/share/qgis/python/plugins

RUN fc-cache -f && fc-list | sort

# Add entrypoint
COPY entrypoint.sh /entrypoint.sh

EXPOSE 80

VOLUME ["/data"]

ENTRYPOINT ["/entrypoint.sh"]
```

My entrypoint.sh
```sh
#!/bin/bash
set -e

echo "Mounting cifs volume QGIS..."
mkdir -p [...]
mount -t cifs [...] -o user=${QGIS_CIFS_USER},password=${QGIS_CIFS_PASSWORD},domain=,uid=0,iocharset=utf8,vers=2.1,noperm,noserverino
echo "QGIS cifs mount successful!"

# Substitute variables from ENV
envsubst < /etc/apache2/templates/qgis-server.conf.template > /etc/apache2/sites-enabled/qgis-server.conf

# Activate the Ubuntu Apache environment
. /etc/apache2/envvars

exec /usr/sbin/apache2 -k start -DFOREGROUND
```
Any ideas would be very helpful, thanks!

**Comment by danceb** [comment]
I modified the comment above, because the mounts of the fonts and plugin folders where not correctly. Changed it to the folders mentioned in the readme, but still getting the same errors. 

I tried to set the environmental variable `FcgidInitialEnv QT_QPA_FONTDIR "/usr/local/share/fonts"` within `qgis-server.conf.template` related to https://github.com/qgis/QGIS/issues/51688, but this doesn't change anything.

How can we detect, if this is a issue which comes from the qgis server itself or from the adjustments made while building a custom image based on it?

**Comment by manisandro** [comment]
@HusseinKabbout Any ideas?

**Comment by danceb** [comment]
To simplify the test case more, I left over my own building attempts with a custom Dockerfile and entrypoint.sh and just pulled your image and configured it within the docker-compose.yml and mount the font folder there:
```
  qwc-qgis-server:
    image: sourcepole/qwc-qgis-server:3.28.6
    restart: unless-stopped
    volumes:
      - ./volumes/qgs-resources/stage:/data:ro
      - ./volumes/geodata/stage:/geodata:ro
      - ./pg_service.stage.conf:/etc/postgresql-common/pg_service.conf:ro
      - ./qwc-qgis-server/fonts:/usr/local/share/fonts
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor=unconfined
``` 
until 3.28.5 the legend is generated correctly with the mounted custom font and since 3.28.6 this does not work anymore.
